[package]
name = "doom_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.34.0"
glutin = "0.31.3"
glutin-winit = "0.4.2"
obj = "0.10.2"
raw-window-handle = "0.6.0"
winit = "0.29.12"
